/**
 * CF Workers environment — bindings, secrets, vars.
 *
 * `cloudflare:workers` is a virtual module injected by the CF runtime.
 * Types come from wrangler.d.ts (generated by `npm run cf-typegen`).
 *
 * Usage (server-only — inside createServerFn or Hono handlers):
 *   import { env } from '~/lib/env'
 *   const rows = await env.DB.prepare('SELECT 1').all()
 *   const kv = env.KV
 */

export { env } from 'cloudflare:workers';
